# Создание и заполнение данных БД Postgre

In [2]:
%pip install python-dotenv psycopg2-binary
%pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: python-dotenv in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (1.2.2)
Requirement already satisfied: psycopg2-binary in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (2.9.11)
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\Ivan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import os
import json
import psycopg2
import pandas as pd
from psycopg2.extras import DictCursor
from dotenv import load_dotenv

# Получение секретов

In [5]:
# получаем текущую директорию ноутбука 
current_dir = os.getcwd()

# переходим на один уровень вверх
project_root = os.path.dirname(current_dir)

# формируем путь к файлу .env в папке Task1, там у нас лежит файл .env с настройками подключения к БД
dotenv_path = os.path.join(project_root, 'task_2_Docker', '.env')

# загружаем переменные окружения из указанного файла
load_dotenv(dotenv_path)

# получим доступ к переменным окружения
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
db_name = os.getenv("DB_NAME")
db_port = os.getenv("DB_PORT") 
secret_hash = os.getenv("SECRET_HASH") 

print(f"Загруженные данные: USER={user}, DB={db_name}, DB_PORT={db_port}")

Загруженные данные: USER=Davydoff, DB=my_db_Davydoff, DB_PORT=5433

# Подключение к базе данных PostgreSQL

In [7]:
conn = None
try:
    conn = psycopg2.connect(
        host="localhost", # если Docker контейнер запущен локально, а ноутбук вне Docker.
                          # НО! если ноутбук также в Docker и в одной сети с БД,
                          # то нужно использовать имя сервиса Docker (например, 'db' или 'postgres_db').
        database=db_name,
        user=user,
        password=password,
        port=db_port
    )
    cursor = conn.cursor()

    print("Успешное подключение к базе данных!")
    
except Exception as e:
    print(f"Ошибка при подключении к базе данных: {e}")

Успешное подключение к базе данных!

In [8]:
# пример запроса
cursor.execute("SELECT version();")
db_version = cursor.fetchone()
print(f"Версия PostgreSQL: {db_version}")

Версия PostgreSQL: ('PostgreSQL 13.23 (Debian 13.23-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit',)

In [9]:
# получить список таблиц:
cursor.execute("""
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
""")
tables = cursor.fetchall()
print("\nТаблицы в базе данных:")
for table in tables:
    print(f"- {table[0]}")

Таблицы в базе данных:
- departments
- user_logs

In [10]:
# закрытие соединения с БД - После завершения работы с БД не забываем закрывать соединение!
cursor.close()
conn.close()

Вам предоставлена БД с логами (действиями) студентов на образовательном портале за весенний семестр (агрегация по каждой неделе) по отдельному электронному курсу - таблица user_logs (примечание. создана в предыдущих л.р.).
- сourseid — уникальный идентификатор курса, дисциплины;
- userid — уникальный идентификатор студента (не используется в обучении);
- num_week — номер недели в году;
- s_all — количество всех событий на текущий момент;
- s_all_avg — среднее количество всех событий в неделю;
- s_course_viewed — количество просмотров курса;
- s_course_viewed_avg — среднее количество просмотров курса в неделю;
- s_q_attempt_viewed — количество просмотров теста;
- s_q_attempt_viewed_avg — среднее количество просмотров теста в неделю;
- s_a_course_module_viewed — количество просмотров модуля в курсе;
- s_a_course_module_viewed_avg — среднее количество просмотров модуля в курсе в неделю;
- s_a_submission_status_viewed — количество отправленных заданий на проверку;
- s_a_submission_status_viewed_avg — среднее количество ответов;
- namer_level — оценка за дисциплину;
- depart — номер кафедры;
- name_osno — основа обучения (имеет два значения: бюджет или контракт);
- name_formopril — форма обучения;
- leveled — уровень образования (имеет два значения: бакалавриат, магистратура, специалитет, магистратура);
- num_sem — номер семестра;
- kurs — номер курса учебной группы.

Также в таблице  departments хранятся названия кафедр, таблица связана с логами по полю depart:
id - код кафедры;
name - сокращенное название кафедры.

## Задание 1 (если до этого еще этот шаг не был выполнен):

Измените данные вещественного типа, сейчас целая и дробная часть разделены запятой, замените ее на точку. 

Выведите первые 10 записей, чтобы проверить результат предобработки.

In [31]:
# получаем текущую директорию ноутбука 
current_dir = os.getcwd()

# переходим на один уровень вверх
project_root = os.path.dirname(current_dir)

# формируем путь к файлу .env в папке Task1, там у нас лежит файл .env с настройками подключения к БД
dotenv_path = os.path.join(project_root, 'task_2_Docker', '.env')

# загружаем переменные окружения из указанного файла
load_dotenv(dotenv_path)

# получим доступ к переменным окружения
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")
db_name = os.getenv("DB_NAME")
db_port = os.getenv("DB_PORT") 
secret_hash = os.getenv("SECRET_HASH") 

print(f"Загруженные данные: USER={user}, DB={db_name}, DB_PORT={db_port}")

Загруженные данные: USER=Davydoff, DB=my_db_Davydoff, DB_PORT=5433

In [ ]:
conn = None
try:
    conn = psycopg2.connect(
        host="localhost",
        database=db_name,
        user=user,
        password=password,
        port=db_port
    )
    cursor = conn.cursor()

    print("Успешное подключение к базе данных!")
    
except Exception as e:
    print(f"Ошибка при подключении к базе данных: {e}")

conn.autocommit = True

Успешное подключение к базе данных!

In [15]:
query = "SELECT * FROM USER_LOGS ORDER BY RANDOM() LIMIT 10"
cursor.execute(query)
rows = cursor.fetchall()

columns = [desc[0] for desc in cursor.description]
print(f"Колонки: {columns}\n")

for row in rows:
    print(row)

Колонки: ['courseid', 'userid', 'num_week', 's_all', 's_all_avg', 's_course_viewed', 's_course_viewed_avg', 's_q_attempt_viewed', 's_q_attempt_viewed_avg', 's_a_course_module_viewed', 's_a_course_module_viewed_avg', 's_a_submission_status_viewed', 's_a_submission_status_viewed_avg', 'namer_level', 'name_vatt', 'depart', 'name_osno', 'name_formopril', 'leveled', 'num_sem', 'kurs', 'date_vatt']

(71987, 32351, 25, 4, 9.25, 2, 4.6, 0, 0.0, 1, 2.3, 1, 2.3, 4, 'Экзамен', 21, 2, 2, 1, 4, 3, datetime.date(2022, 6, 29))
(76293, 33729, 22, 1, 1.0588, 1, 0.3529, 0, 0.0, 0, 0.0588, 0, 0.0588, 2, 'Экзамен', 41, 2, 1, 1, 2, 2, datetime.date(2022, 6, 27))
(72359, 30743, 22, 0, 0.1176, 0, 0.0588, 0, 0.0, 0, 0.0, 0, 0.0, 2, 'Экзамен', 16, 1, 1, 1, 4, 3, datetime.date(2022, 6, 20))
(73090, 21392, 8, 0, 0.0, 0, 0.0, 0, 0.0, 0, 0.0, 0, 0.0, 2, 'Экзамен', 17, 2, 2, 1, 6, 4, datetime.date(2022, 6, 15))
(78272, 23605, 23, 0, 0.0, 0, 0.0, 0, 0.0, 0, 0.0, 0, 0.0, 5, 'Экзамен', 11, 2, 2, 1, 8, 5, datetime.date(2022, 6, 15))
(75970, 33792, 8, 0, 27.0, 0, 7.3333, 0, 0.0, 0, 7.0, 0, 4.6667, 4, 'Экзамен', 15, 1, 1, 2, 2, 2, datetime.date(2022, 6, 27))
(79426, 27665, 18, 0, 0.0769, 0, 0.0769, 0, 0.0, 0, 0.0, 0, 0.0, 3, 'Экзамен', 7, 1, 2, 2, 4, 3, datetime.date(2022, 6, 25))
(78263, 36169, 28, 0, 8.7826, 0, 2.4783, 0, 0.087, 0, 2.1739, 0, 1.913, 5, 'Экзамен', 11, 2, 2, 1, 2, 2, datetime.date(2022, 7, 1))
(76411, 34445, 20, 0, 32.8667, 0, 8.6667, 0, 0.0, 0, 9.9333, 0, 8.2, 5, 'Экзамен', 12, 1, 1, 2, 2, 2, datetime.date(2022, 6, 30))
(72003, 27148, 7, 0, 0.0, 0, 0.0, 0, 0.0, 0, 0.0, 0, 0.0, 3, 'Экзамен', 21, 1, 2, 1, 6, 4, datetime.date(2022, 7, 1))

In [16]:
query = "SELECT * FROM USER_LOGS ORDER BY RANDOM() LIMIT 10"
df = pd.read_sql_query(query, conn)
display(df)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_16800\1171977693.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

,courseid,userid,num_week,s_all,s_all_avg,s_course_viewed,s_course_viewed_avg,s_q_attempt_viewed,s_q_attempt_viewed_avg,s_a_course_module_viewed,...,s_a_submission_status_viewed_avg,namer_level,name_vatt,depart,name_osno,name_formopril,leveled,num_sem,kurs,date_vatt
0,88721,36728,10,0,0.0000,0,0.0000,0,0.0,0,...,0.0000,2,Экзамен,43,2,2,1,2,2,2022-06-29
1,88347,24500,19,0,0.0000,0,0.0000,0,0.0,0,...,0.0000,2,Экзамен,30,2,1,1,6,4,2022-06-22
2,74969,33668,22,0,0.1176,0,0.1176,0,0.0,0,...,0.0000,5,Экзамен,3,1,1,3,2,2,2022-06-25
3,76568,25994,16,55,15.0909,18,4.4545,0,0.0,14,...,3.6364,3,Экзамен,24,2,1,2,8,5,2022-06-27
4,72232,27685,21,0,0.6250,0,0.6250,0,0.0,0,...,0.0000,3,Экзамен,37,1,2,1,6,4,2022-06-24
5,88856,35662,16,2,5.0000,2,2.7273,0,0.0,0,...,0.5455,4,Экзамен,22,1,1,1,2,2,2022-06-27
6,75833,36046,6,1,1.0000,1,1.0000,0,0.0,0,...,0.0000,2,Экзамен,8,1,1,2,2,2,2022-06-18
7,84979,23135,11,0,0.0000,0,0.0000,0,0.0,0,...,0.0000,4,Экзамен,9,2,2,1,8,5,2022-06-20
8,71571,33391,29,0,5.7917,0,0.8750,0,3.0,0,...,0.0833,4,Экзамен,20,1,1,1,2,2,2022-06-21
9,88979,34149,16,0,1.0000,0,0.6364,0,0.0,0,...,0.0000,5,Экзамен,4,1,1,3,2,2,2022-07-06

## Задание 2: 

Выведите количество кафедр, за которыми закреплены курсы на портале.

In [17]:
query = """
    SELECT 
        COUNT(DISTINCT depart) AS departments_count
    FROM USER_LOGS
    WHERE courseid IS NOT NULL
"""

df = pd.read_sql_query(query, conn)
display(df)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_16800\3608507271.py:8: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

   departments_count
0                 43

##  Задание 3:

Выведите сколько у каждой кафедры закреплено электронных курсов на портале. 
Требуется выводить сокращенное название кафедры и количество курсов. 
У какой кафедры больше всего курсов на портале?

In [20]:
query = """
    SELECT 
        DEPARTMENTS.name AS DEPTNAME,
        COUNT(USER_LOGS.courseid) AS COUNTCOURSE
    FROM USER_LOGS INNER JOIN DEPARTMENTS ON USER_LOGS.depart = DEPARTMENTS.id
    GROUP BY DEPARTMENTS.name
    ORDER BY COUNTCOURSE DESC
"""

df = pd.read_sql_query(query, conn)
display(df)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_16800\1262581724.py:10: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

     deptname  countcourse
0        МиХТ        25296
1        ДиСО        25176
2         ЛиП        19008
3        РМПИ        17856
4     ГМДиОПИ        16968
5         ТОМ        16704
6       БИиИТ        16176
7        ПОиД        14760
8       АЭПиМ        14232
9       ЛиУТС        13440
10       ПиСЗ        13248
11     ГМУиУП        12144
12     ГМиТТК        11952
13    Эконом.        11928
14    МиТОДиМ        11760
15       ВТиП        11232
16       ИиИБ        10608
17     ПиЭММО         9864
18       ЛПиМ         9768
19    Психол.         9552
20         CC         9504
21       ЭиМЭ         9192
22    РЯОЯиМК         8736
23       ТССА         7872
24         ВИ         7848
25   Менеджм.         7848
26        ЯиЛ         7488
27        ЭПП         7368
28       АиИИ         6816
29      Химии         6000
30        АСУ         5640
31       ПМиИ         5544
32        ХОМ         5280
33    Дизайна         5088
34       ТиЭС         5016
35       УиИС         4200
36     СРиППО         3864
37     ПЭиБЖД         3840
38     Физики         3480
39       ЦДОМ          984
40  Физкульт.          504
41        ИТМ          504
42      УСиБА          240

## Задание 4:

Ответьте на вопрос: существуют ли курсы, за которыми закреплено несколько кафедр? Если такие курсы есть, то выведите их количество.
Также выведите названия кафедр, которые совместно преподают один и тот же курс.

In [32]:
query = """

    SELECT 
        COUNT(DEPTCOUNT.courseid)
    FROM 
    (
        SELECT
            USER_LOGS.courseid,
            COUNT(DISTINCT USER_LOGS.depart) AS departments_count
        FROM USER_LOGS
        WHERE courseid IS NOT NULL
        GROUP BY USER_LOGS.courseid
        HAVING COUNT(DISTINCT depart) > 1
    ) AS DEPTCOUNT 
"""



df = pd.read_sql_query(query, conn)
display(df)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_16800\866560846.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

   count
0     60

In [ ]:
#получили курсы, на которые закреплены несколько кафедр
query = """
    SELECT
        USER_LOGS.courseid AS COURSEID,
        COUNT(DISTINCT USER_LOGS.depart) AS DEPCOUNT
    FROM
        USER_LOGS
    GROUP BY USER_LOGS.courseid
    HAVING COUNT(DISTINCT USER_LOGS.depart) > 1
"""

#мы должны теперь найти уникальные кафедры, сравнивая их курсы с курсами, имеющими несколько кафедр
#тем самым на каждый курс получим кафедры, которые закреплены именно на один курс.
query = """

    WITH COURSRES AS 
    (
	SELECT
		USER_LOGS.courseid AS COURSEID,
		COUNT(DISTINCT USER_LOGS.depart) AS DEPCOUNT
	FROM
		USER_LOGS
	GROUP BY USER_LOGS.courseid
	HAVING COUNT(DISTINCT USER_LOGS.depart) > 1
    )

    SELECT DISTINCT
	    DEPARTMENTS.name,
	    UL.courseid
    FROM USER_LOGS AS UL
	    INNER JOIN DEPARTMENTS ON UL.DEPART = DEPARTMENTS.ID
	    INNER JOIN COURSRES ON UL.COURSEID = COURSRES.COURSEID
"""


df = pd.read_sql_query(query, conn)
display(df)

C:\Users\Ivan\AppData\Local\Temp\ipykernel_16800\874770190.py:24: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query(query, conn)

    courseid  depcount
0      71495         3
1      71508         2
2      71541         2
3      71547         2
4      71549         2
5      71571         3
6      71632         2
7      71736         2
8      71852         2
9      71857         2
10     71884         2
11     71892         3
12     71904         2
13     72126         2
14     72314         2
15     72347         2
16     72358         2
17     72359         3
18     72380         4
19     72392         3
20     72402         4
21     72416         3
22     72447         3
23     72457         4
24     72460         3
25     72462         2
26     72469         2
27     72800         2
28     72865         2
29     72885         3
30     73574         2
31     73986         2
32     75810         3
33     75833         4
34     75834         3
35     75839         3
36     75849         3
37     76293         2
38     78057        25
39     79426         4
40     81847         2
41     82754         2
42     82755         2
43     83853         3
44     84103         2
45     84140         2
46     84352         2
47     84834         3
48     86712         2
49     87097         2
50     87396         3
51     87935         2
52     88349         2
53     88415         3
54     88594         2
55     88598         2
56     88603         2
57     88653         2
58     88659         2
59     88888         2

## Задание 5:

Выведите количество студентов, которые получили 2, 3, 4, 5.

Пример вывода:

| namer_level |	count |
|-----|------|
|2 |	4 |
|3 |	3435 |
|4 | 	4676765|
|5 | 232 |

## Задание 6:

Выведите студента, который больше всех работает на портале (у него максимальное количество логов за вест период обучения).

## Задание 7:

Выведите по каждой недели среднее количество всех событий на портале.

## Задание 8: 

Выведите название кафедры, у которой больше всего отличников.

Отдельно выведите название кафедры, у которой больше всего двоечников.

## Задание 9:
Провести анализ пиковой активности студентов перед экзаменом (с использованием (Common Table Expression — CTE), оператор with).

Вывести, на какой неделе семестра студенты проявляли наибольшую активность в курсе в целом, и как эта активность распределяется между студентами-бюджетниками и контрактниками.

Пример вывода :

| name_osno | week_number	| avg_s_all	| avg_s_course_viewed |	avg_s_q_attempt_viewed |
|-----|------|------|------|------|
| бюджет |	14	| 125.45 |	45.67 |	32.12 |
|контракт |	14	| 98.76 |	38.90 |	25.43 |